### ISSUE TITLE
Nothing happens when Application - Open track is clicked, but an error

### ISSUE THREAD

**Issue by alessio** [sigurdga/maps#5]
Hi there,

forwarding here a bug report I got through Debian's BTS:

> Package: openstreetmap-client
> Version: 12.07.4~ds0-1
> Severity: normal
> Tags: upstream
> 
> Dear Maintainer,
> 
> When clicking Application - Open track, nothing happens, but the following
> error is printed on the console:
> 
> Traceback (most recent call last):
>   File "/usr/share/openstreetmap-client/maps/map_application.py", line 141,
> in on_open
>     self.window.on_import_clicked(action, parameter)
> TypeError: on_import_clicked() takes exactly 2 arguments (3 given)
> 
> -- System Information:
> Debian Release: jessie/sid
>   APT prefers unstable
>   APT policy: (500, 'unstable'), (500, 'testing'), (500, 'stable'), (1, 'experimental')
> Architecture: amd64 (x86_64)
> Foreign Architectures: i386
> 
> Kernel: Linux 3.9-1-amd64 (SMP w/8 CPU cores)
> Locale: LANG=C, LC_CTYPE=C (charmap=ANSI_X3.4-1968)
> Shell: /bin/sh linked to /bin/bash
> 
> Versions of packages openstreetmap-client depends on:
> ii  dconf-gsettings-backend [gsettings-backend]  0.16.0-4
> ii  gir1.2-champlain-0.12                        0.12.3-2
> ii  gir1.2-clutter-1.0                           1.10.8-2
> ii  gir1.2-gdkpixbuf-2.0                         2.28.2-1
> ii  gir1.2-glib-2.0                              1.36.0-2+b1
> ii  gir1.2-gtk-3.0                               3.8.2-2
> ii  gir1.2-gtkchamplain-0.12                     0.12.3-2
> ii  gir1.2-gtkclutter-1.0                        1.2.0-2
> ii  python                                       2.7.5-2
> ii  python-lxml                                  3.2.0-1

It should be something pretty easy to solve, unfortunately I don't have so much time to provide you a patch shortly.

**Comment by sigurdga** [comment]
Fixed in next version. Yes, it was kind of easy to fix. Sorry for the delay.
